version: "3.7"
services:
  simulator-scheduler:
    image: simulator-scheduler
    container_name: simulator-scheduler
    restart: always
    tty: true
    networks:
      - simulator-internal-network
    depends_on:
      - simulator-cluster
    environment:
      - KUBECONFIG=/config/kubeconfig.yaml
    volumes:
      - sched-conf:/config
  simulator-server:
    image: simulator-server
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-cluster:2379
      - KUBE_APISERVER_URL=http://simulator-cluster:3131
      - KUBE_SCHEDULER_CONFIG_PATH=/config/scheduler.yaml
    ports:
      - "1212:1212"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sched-conf:/config
  simulator-frontend:
    image: simulator-frontend
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3131
    ports:
      - "3000:3000"
    tty: true
  simulator-cluster:
    image: registry.k8s.io/kwok/cluster:v0.5.1-k8s.v1.29.0
    container_name: simulator-cluster
    restart: always
    ports:
      - "3131:3131"
    volumes:
      - simulator-etcd-data:/var/lib/etcd
      - ./kwok.yaml:/root/.kwok/kwok.yaml
    environment:
      - KWOK_KUBE_APISERVER_PORT=3131
    networks:
      - simulator-internal-network
networks:
  simulator-internal-network:
    driver: bridge
volumes:
  simulator-etcd-data:
  sched-conf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/simulator/cmd/scheduler
      o: bind
