---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: scenario-webhook-service
        namespace: scenario-system
        path: /validate-simulation-kube-scheduler-simulator-x-k8s-io-v1alpha1-scenario
        port: 9443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsRENDQW55Z0F3SUJBZ0lVT2xINFV2dE5FUWJvWXZSUWIvL0Q4M2xWQlBrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd056RTFNRE1HQTFVRUF3d3NjMk5sYm1GeWFXOHRkMlZpYUc5dmF5MXpaWEoyYVdObExuTmpaVzVoY21sdgpMWE41YzNSbGJTNXpkbU13SGhjTk1qVXdOVEV3TURjME1qVTJXaGNOTXpVd05UQTRNRGMwTWpVMldqQTNNVFV3Ck13WURWUVFEREN4elkyVnVZWEpwYnkxM1pXSm9iMjlyTFhObGNuWnBZMlV1YzJObGJtRnlhVzh0YzNsemRHVnQKTG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUppNVhsdzk0VXRqL3BwZwpjVWNqWFBxcjF5anY2WjZSODE0bnlqbEh6MGpOeVhabm9EdE9KYTVJZXdCVVZQM0VnakYyOUR2R01mNW1hS2RLCmdLZ2hTVkJsMlY3Q3pZUjdvYWJJalFJTHZ3ZUh0UzJxb2pQcDB2TzNwWkxaS0Z4b2RGREw3WnBrdFRBN3dUTHIKb2EwdUozaUd0K1RtUUs3RkFxWldTa0xiQURVdWVwY0RyUU1UNFNTSi91aEJ6SFYxZG5qekx6bWJjb21HSFNqYwpHcFMwWkwrMWoyYW55aWUzR0s1Nlg2THU3eERCRlU5WDBlb1pLdFA2bVRkMGkrWllCb05sOS9ZdU5DVm5RTkJzCnk1VDlJWFFVMzlPYXRBbmpVTC8xUGtHMGZXb2xUUmw5UEo3bmlsUXYxVWNKNGVyNUhtNStibG1LUUxQemdUWHYKeWYwMjdFRUNBd0VBQWFPQmx6Q0JsREJ6QmdOVkhSRUViREJxZ2l4elkyVnVZWEpwYnkxM1pXSm9iMjlyTFhObApjblpwWTJVdWMyTmxibUZ5YVc4dGMzbHpkR1Z0TG5OMlk0STZjMk5sYm1GeWFXOHRkMlZpYUc5dmF5MXpaWEoyCmFXTmxMbk5qWlc1aGNtbHZMWE41YzNSbGJTNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQWRCZ05WSFE0RUZnUVUKUDhPNGZKM2FTYVFNczRGMTFjaUdMajlSZFpJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFeHdDRzNnblNJRgp6TWpFSk9JK3hTMUNzTWJNRzdQbEZJd2xVV3NNUVZ4Yy9uaEdPekpQTG55RXVUSkdoODlQSVFndW9Jc2lIOCtpCnZwcHQrNnZVVmNScHdtbVZxYVRlcEFndWRSWEJ4ODdlc1hoZGR4ZDdvWTA4R0RVaG1nUk1Iait5M3V1YWMxMloKMXh2dUVwWk80Z2RIVzBYZEE5aTBnbGJuVFZFd3Y4RlpRN2ptSEFjSjhaMTEyUUNNWGlOeUdZbzZhZmdUVFlTcApUaDMzeUEwRFp6S3NsajlmTTBXeTVqczdMTmJkTHB6QVR6UU5rR2d2L1ZUL3pQbXFBOWtkOEJaWWpqTlZMWlI1CkVnUGNsSkgzaTZCRitvYTMzRS8wT2hkSXhlWjczdmNCcnFCYUNzNmp5cDlvRHN4NHBVeU9UYjE1UGQ1cUZBU0wKdmVSVG1naUEzQjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    failurePolicy: Fail
    name: vscenario-v1alpha1.kb.io
    rules:
      - apiGroups:
          - simulation.kube-scheduler-simulator.x-k8s.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - scenarios
    sideEffects: None
